import { Inter } from "next/font/google";
import Header from "../_component/Header"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className='context'>
          {children}
        </div >
      </body>
    </html>
  );
}
