# Generated by Django 3.1.4 on 2024-07-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smoke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('count', models.PositiveSmallIntegerField()),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
